### ISSUE TITLE
measurement_id cannot be trusted

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#70] opened 2017-07-25 11:53 UTC
Since `measurement_id` is generated on the client-side, it cannot be trusted and we should not be using it as a key assuming it is unique. I have found some instances of pathologically broken measurement_id's (where they are basically the same throughout the whole report file) and as such we should be re-generating it server-side.

See this file as an example:

`2017-01-05/20170104T015449Z-PT-AS3243-web_connectivity-20170104T105911Z_AS3243_OadZCx9yRNvqKYsLQaQDa3c1swLofXEQNtcplXQ14QrXemKcCT-0.2.0-probe.json`

**Comment by darkk** [comment] 2017-07-25 11:57
> we should be re-generating it server-side

IMHO, we should not call it `measurement_id` then because of ~backward compatibility~ sanity.

**Comment by hellais** [comment] 2017-07-25 11:59
> IMHO, we should not call it measurement_id then because of backward compatibility sanity.

Fair enough, in any case this is creating a few issues with the measurement API as this API call is not really working as it should: https://github.com/TheTorProject/ooni-measurements/blob/master/measurements/api/measurements.py#L159

**Comment by darkk** [comment] 2019-02-22 19:39
I consider this ticket a duplicate of #48, so I'm closing it.

Also, #48 is half-solved by [OONI OOID](https://github.com/ooni/pipeline/blob/master/docs/ooni-uuid.md). The OONI OOID will eventually be stamped on historical measurements when corresponding part of OONI Collector will be rolled out (stamping OOID on new measurements in unique way).

**Closed as completed by darkk** 2019-02-22 19:39 UTC
