### ISSUE TITLE
Support filtering for all test_names

### ISSUE THREAD

**Issue by hellais** [ooni/pipeline#103] opened 2017-11-09 12:42 UTC
Currently DASH data is not added to metadb because the ENUM does not include dash as a supported test.

**Comment by darkk** [comment] 2017-11-09 12:46
Looks like a bug, alike measurement should be ingested but have `NULL` instead of correct ENUM value.

**Comment by hellais** [comment] 2017-11-09 12:49
Yes you are right, they are ingested (as I confirm by running: `SELECT * FROM report WHERE report.textname LIKE '%dash%' AND probe_cc = 'US' LIMIT 10;`), however they should have the `test_name` column set otherwise they will not be searchable by the API or easy to filter for.

**Comment by hellais** [comment] 2018-01-02 11:09
I suspect the same thing is happening with test_name=telegram

**Comment by darkk** [comment] 2019-05-30 15:52
That should be probably closed as a duplicate of #119 (having more precise description).

**Closed as completed** 2019-11-19 14:14 UTC
